# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import booking_pb2 as booking__pb2

GRPC_GENERATED_VERSION = '1.75.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in booking_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TicketingStub(object):
    """The main service for our ticketing system.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Login = channel.unary_unary(
                '/booking.Ticketing/Login',
                request_serializer=booking__pb2.LoginRequest.SerializeToString,
                response_deserializer=booking__pb2.LoginResponse.FromString,
                _registered_method=True)
        self.AddTravelService = channel.unary_unary(
                '/booking.Ticketing/AddTravelService',
                request_serializer=booking__pb2.AddServiceRequest.SerializeToString,
                response_deserializer=booking__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.ListAvailableServices = channel.unary_unary(
                '/booking.Ticketing/ListAvailableServices',
                request_serializer=booking__pb2.ListServicesRequest.SerializeToString,
                response_deserializer=booking__pb2.ListServicesResponse.FromString,
                _registered_method=True)
        self.BookSeats = channel.unary_unary(
                '/booking.Ticketing/BookSeats',
                request_serializer=booking__pb2.BookSeatsRequest.SerializeToString,
                response_deserializer=booking__pb2.BookingResponse.FromString,
                _registered_method=True)


class TicketingServicer(object):
    """The main service for our ticketing system.
    """

    def Login(self, request, context):
        """Handles login for both Admins and Customers.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddTravelService(self, request, context):
        """An Admin-only function to add a new travel service.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListAvailableServices(self, request, context):
        """A Customer function to view all available services for a given date.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BookSeats(self, request, context):
        """A Customer function to book one or more seats on a service.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TicketingServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Login': grpc.unary_unary_rpc_method_handler(
                    servicer.Login,
                    request_deserializer=booking__pb2.LoginRequest.FromString,
                    response_serializer=booking__pb2.LoginResponse.SerializeToString,
            ),
            'AddTravelService': grpc.unary_unary_rpc_method_handler(
                    servicer.AddTravelService,
                    request_deserializer=booking__pb2.AddServiceRequest.FromString,
                    response_serializer=booking__pb2.StatusResponse.SerializeToString,
            ),
            'ListAvailableServices': grpc.unary_unary_rpc_method_handler(
                    servicer.ListAvailableServices,
                    request_deserializer=booking__pb2.ListServicesRequest.FromString,
                    response_serializer=booking__pb2.ListServicesResponse.SerializeToString,
            ),
            'BookSeats': grpc.unary_unary_rpc_method_handler(
                    servicer.BookSeats,
                    request_deserializer=booking__pb2.BookSeatsRequest.FromString,
                    response_serializer=booking__pb2.BookingResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'booking.Ticketing', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('booking.Ticketing', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Ticketing(object):
    """The main service for our ticketing system.
    """

    @staticmethod
    def Login(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/booking.Ticketing/Login',
            booking__pb2.LoginRequest.SerializeToString,
            booking__pb2.LoginResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddTravelService(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/booking.Ticketing/AddTravelService',
            booking__pb2.AddServiceRequest.SerializeToString,
            booking__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListAvailableServices(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/booking.Ticketing/ListAvailableServices',
            booking__pb2.ListServicesRequest.SerializeToString,
            booking__pb2.ListServicesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BookSeats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/booking.Ticketing/BookSeats',
            booking__pb2.BookSeatsRequest.SerializeToString,
            booking__pb2.BookingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
